//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuLookWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class denuncia
    {
        public int id { get; set; }
        public string Descricao { get; set; }
        public string Usuarios_cloudId { get; set; }
        public int FotoPosts_IdPost { get; set; }
    
        public virtual fotoposts fotoposts { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
