//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuLookWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotoposts
    {
        public fotoposts()
        {
            this.avaliacoes = new HashSet<avaliacoes>();
            this.denuncia = new HashSet<denuncia>();
        }
    
        public int IdPost { get; set; }
        public System.DateTime DataPost { get; set; }
        public string ImagemPost { get; set; }
        public string Usuarios_cloudId { get; set; }
    
        public virtual ICollection<avaliacoes> avaliacoes { get; set; }
        public virtual ICollection<denuncia> denuncia { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
