//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuLookWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class meulookEntities : DbContext
    {
        public meulookEntities()
            : base("name=meulookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<avaliacoes> avaliacoes { get; set; }
        public virtual DbSet<denuncia> denuncia { get; set; }
        public virtual DbSet<fotoposts> fotoposts { get; set; }
        public virtual DbSet<notas> notas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
