//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuLookWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.denuncia = new HashSet<denuncia>();
            this.fotoposts = new HashSet<fotoposts>();
        }
    
        public string cloudId { get; set; }
        public long QtdeAvaliacao { get; set; }
        public int Alcance { get; set; }
    
        public virtual ICollection<denuncia> denuncia { get; set; }
        public virtual ICollection<fotoposts> fotoposts { get; set; }
    }
}
